### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by jku-sr** [Barben360/VPNUnlimited2Syno#2]
administrator@Synology:/volume1/Shared/VPNUnlimited2Syno$ python "Setup"
  File "Setup", line 12
    print("#############################################",flush=True)
                                                               ^
SyntaxError: invalid syntax
administrator@Synology:/volume1/Shared/VPNUnlimited2Syno$

**Comment by Barben360** [comment]
When you run:
`python "Setup"`
the system runs the default Python version, which must be 2.7 in your case.
This is why I told in the readme to install Python 3 and run using:
`./Setup`
because the first line of "Setup" script forces to run Python 3. If you don't want to do that, you can still run:
`python3 "Setup"`
